[package]
name = "webshare-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version ="1.0.216", features = ["derive"] }
serde_derive = "1.0.216"
serde_json = "1.0.134"
serde_with = "3.11.0"
url = "2.5.4"
